### ISSUE TITLE
Generator's Connector ignores actual gradle wrapper.

### ISSUE THREAD

**Issue by quidryan** [nebula-plugins/nebula-test#10]
Tooling API will try to download your version of gradle from service.gradle.org, irrelevant if the wrapper being used actually came from there. Meaning that internally since we use a custom distribution internally, the Connector doesn't work since it's trying to download distribution in from service.gradle.org. You can see this logic in org.gradle.tooling.internal.consumer.DistributionFactory:

```
private Distribution getDownloadedDistribution(String gradleVersion) {
    URI distUri = new DistributionLocator().getDistributionFor(GradleVersion.version(gradleVersion));
    return getDistribution(distUri);
}
```

Either see if this was fixed in a new Gradle, or start writing out a gradle/wrapper/gradle-wrapper.properties when generating the repo projects.

**Comment by jmcgarr** [comment]
Already fixed. Closing.
