### ISSUE TITLE
Ivy `patternLayout` breaks backwards compatiblity

### ISSUE THREAD

**Issue by DPUkyle** [nebula-plugins/nebula-test#108]
The use of `patternLayout` in n.t.d.GradleDependencyGenerator breaks backwards compatibility with Gradle 4.x. It appears [this change](https://github.com/nebula-plugins/nebula-test/commit/682120f1f625152ef4374b2d0ba77300fcf63c4e#diff-3d6a543bf940ebce87358f1aa313071dR99) causes the problem. `patternLayout` is added in Gradle 5, so invoking this class will result in an error like:
```
org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method patternLayout() for arguments [build_e435034qi9j7da3zn5b1hmt0p$_run_closure1$_closure2$_closure3$_closure5$_closure6@36195c5f] on object of type org.gradle.api.internal.artifacts.repositories.DefaultIvyArtifactRepository.
```

I didn't see anything in the changelog or readme indicating that Gradle 4 was no longer supported.

**Comment by rpalcolea** [comment]
Hi @DPUkyle, let us know if https://github.com/nebula-plugins/nebula-test/releases/tag/v7.1.9 works for you or if you would like to see another way to get this.

**Comment by DPUkyle** [comment]
Hi @rpalcolea. Yes once I get v7.1.9 and change to use the overloaded constructor `GradleDependencyGenerator(Gradle, DependencyGraph, String)`, we are back in business.

Gracias!

**Comment by rpalcolea** [comment]
nice! sorry for the disruption!
