### ISSUE TITLE
7.2.4 not in Maven Central

### ISSUE THREAD

**Issue by szpak** [nebula-plugins/nebula-test#113]
nebula-test 7.2.4 is not in Maven Central:
```
Could not resolve all files for configuration ':funcTestCompileClasspath'.
> Could not find com.netflix.nebula:nebula-test:7.2.4.
  Searched in the following locations:
    - https://repo.maven.apache.org/maven2/com/netflix/nebula/nebula-test/7.2.4/nebula-test-7.2.4.pom
    - https://repo.maven.apache.org/maven2/com/netflix/nebula/nebula-test/7.2.4/nebula-test-7.2.4.jar
```

Maybe there was some issues with syncing between JCenter and Maven Central or some changes from that [commit](https://github.com/nebula-plugins/nebula-test/commit/d7b783c150b7c1284988a930ad568812ebfa2979) broke it.

**Comment by rpalcolea** [comment]
Hi @szpak , 

Thanks for bring this up.

Looking at Travis logs -> https://travis-ci.org/nebula-plugins/nebula-test/builds/520509904

Things went fine from our side. This appears to be an issue between Bintray and MavenCentral sync via https://bintray.com/docs/api/#_sync_version_artifacts_to_maven_central 

Just synced again manually via the API and got back

```
{
    "status": "Successfully synced and closed repo.",
    "messages": [
        "Sync finished successfully."
    ]
}
``` 

We will take a deeper look on this and get back once we solve this issue

**Comment by rpalcolea** [comment]
Hi @szpak ,

We added explicit GPG signing via our bintray plugin https://github.com/nebula-plugins/nebula-bintray-plugin/pull/33 and released a new version of nebula-test

It appears that it takes some time for Bintray to really sync to maven central.

Now you can see versions getting int sync:

https://repo.maven.apache.org/maven2/com/netflix/nebula/nebula-test/7.2.5/ or https://repo1.maven.org/maven2/com/netflix/nebula/nebula-test/7.2.5/

In our last release https://travis-ci.org/nebula-plugins/nebula-test/builds/535020028 you can see the following from the logs:

```
> Task :gpgSignVersion
Caching disabled for task ':gpgSignVersion' because:
  Build cache is disabled
Task ':gpgSignVersion' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
--> POST https://api.bintray.com/gpg/nebula/gradle-plugins/nebula-test/versions/7.2.5 (0-byte body)
<-- 200 OK https://api.bintray.com/gpg/nebula/gradle-plugins/nebula-test/versions/7.2.5 (10232ms, 21-byte body)
nebula-test version 7.2.5 has been signed with GPG key
:gpgSignVersion (Thread[Daemon worker,5,main]) completed. Took 10.246 secs.
:syncVersionToMavenCentral (Thread[Daemon worker,5,main]) started.
> Task :syncVersionToMavenCentral
Caching disabled for task ':syncVersionToMavenCentral' because:
  Build cache is disabled

Task ':syncVersionToMavenCentral' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
--> POST https://api.bintray.com/maven_central_sync/nebula/gradle-plugins/nebula-test/versions/7.2.5 (93-byte body)
<-- 200 OK https://api.bintray.com/maven_central_sync/nebula/gradle-plugins/nebula-test/versions/7.2.5 (81629ms, 92-byte body)
nebula-test version 7.2.5 has been synced to maven central
:syncVersionToMavenCentral (Thread[Daemon worker,5,main]) completed. Took 1 mins 21.642 secs.
:release (Thread[Daemon worker,5,main]) started.
```

Please let me know if you can get in good shape now

**Comment by szpak** [comment]
It looks good. Thanks for your work to bring it back to Maven Central!

**Comment by rpalcolea** [comment]
any time @szpak , apologies for the disruption
