### ISSUE TITLE
Upgrade to Spock 1.0

### ISSUE THREAD

**Issue by davidmichaelkarr** [nebula-plugins/nebula-test#36]
Spock 1.0 has been out for a while now (in internet time, I suppose), and Nebula is only on 0.7.  I got confusing errors until I realized I had to remove my Spock 1.0 dependency for Nebula to work. When is Nebula going to be ported to Spock 1.0?

**Comment by szpak** [comment]
See and track #33.

**Comment by davidmichaelkarr** [comment]
Ah, today's lesson: Check current pull requests before filing issue. :)

**Comment by bmuschko** [comment]
Closing this as a duplicate.
