### ISSUE TITLE
Provide convenient way to clean up test project at test completion

### ISSUE THREAD

**Issue by davidmichaelkarr** [nebula-plugins/nebula-test#39]
After running a bunch of integration tests, my "build/test/<class>" folder has dozens of test project folders.  These will go away when I "clean", and I can manually clean up old ones, but I would think these could be cleaned up a bit automatically.  I could define a finalizing task (not even sure how to do that yet) that removes the test project directory, but I don't know how to determine the name of the folder.  It's entirely possible I would want this folder to stick around if the test fails (or make it easy to toggle it so it doesn't delete it), but if the test succeeds I can't see a good reason to keep it around.

**Comment by quidryan** [comment]
They're left there for debugging. If a test fails, you can cd into it and run gradle to diagnose any problems. Likewise there's no easy way to know that a test past or failed in clean(), so we have to err on the side of caution. If you can figure out how to clean up on only success tests, we'd appreciate the PR. 

That said, you can enable this behavior as a system property, cleanProjectDir. The code is here:

https://github.com/nebula-plugins/nebula-test/blob/gradle-2.2/src/main/groovy/nebula/test/AbstractProjectSpec.groovy#L51

**Comment by davidmichaelkarr** [comment]
Do I have to set that property in the remote process?  I tried just setting that property in a "setup" method in the spec, and it had no effect.

**Comment by davidmichaelkarr** [comment]
Oh, and that's in ProjectSpec, not IntegrationSpec.
