### ISSUE TITLE
How to access plugin or task instances to inject mocks?

### ISSUE THREAD

**Issue by davidmichaelkarr** [nebula-plugins/nebula-test#40]
I'm going to have to test my plugin with some mock objects, which my plugin normally loads from a FQCN and instantiates.  I'm considering how I could refactor my plugin so I could directly inject mock instances for the purposes of testing, instead of having the plugin load the class from a FQCN.  I can see how to refactor the plugin class, but I don't see how I can access the plugin or task class from the spec method so I can inject mocks.

(Have you considered creating a mailing list for usage questions?  Now that Spock has reached 1.0, once nebula-test supports Spock 1.0, you may see an uptick in usage, especially from clueless people like me. :) .)

**Comment by quidryan** [comment]
What kinds of test are you proposing? A ProjectSpec or a IntegrationSpec?

If it's an IntegrationSpec, you won't be able to use Mocks. We're running
the Gradle build as an external process, so the in-memory Mocks will not be
available on the classpath for the child process, AFAIK.

If it's a ProjectSpec, you have the direct objects available and you can
assign class instances directly, so it is possible to assign a Mock to a
task or extension.

If you require a FQCN to a Mock to be looked up, that's a Groovy/Spock
issue. I'm not sure how supported that is.

**Comment by davidmichaelkarr** [comment]
IntegrationSpec, in this case. Seeing as the lookup will be done in a different process than the one that created the mock, that's probably not going to be practical. I guess I'll have to develop hand-coded mocks, then.

**Comment by bmuschko** [comment]
If you want to use Mocks, then `IntegrationSpec` is not the type of test you'll want to use. You'd go with the `ProjectSpec`. Spock 1.0 is now supported with the latest version of this plugin.

You can find the forum on [Google Groups](https://groups.google.com/forum/#!forum/nebula-plugins). Please continue your discussion there if needed.

**Comment by davidmichaelkarr** [comment]
Just so it's clear, I know I can't inject typical mocks using IntegrationSpec.  What I also want to make clear is that just because something is an integration test doesn't mean there are many situations where mocks would be useful.  In the spirit of "each test tests one thing", it would be very convenient if integration tests could be written to test one part of the integration, but mock other pieces. I can certainly understand IntegrationSpec not supporting mocks for technical reasons, but if there was a practical way to make that possible, there should be no reason not to make that available.

In my particular application, most of the things I want to test can only be done with the IntegrationSpec, but some of those tests would be cleaner if I could also use mocks.

**Comment by bmuschko** [comment]
@davidmichaelkarr The naming of `IntegrationSpec` is misleading. It should actually be called `FunctionalSpec` because that's what it is - a functional test. I'd have to see a use case as actual code that demonstrates what you are trying to do. What are you testing? A plugin, a task or some other class? Please provide a GitHub repo with some sample code that demonstrates your use case and I can tell you how to implement the test for it with nebula-test.

**Comment by davidmichaelkarr** [comment]
Ok, good.  Here's my integration test of my plugin:
https://github.com/davidmichaelkarr/GradleYangPlugin/blob/master/src/integTest/groovy/com/att/opnfv/yang/gradle/YangPluginIntegSpec.groovy
.

Note the 'process yang module with no types with mock generator' def.  I
ended up handcoding a mock, which was simple enough, but it would have been
a little cleaner as a real mock.

**Comment by bmuschko** [comment]
I'd not test this functionality on the level of the plugin. Instead I'd test `YangGenerateTask` with `ProjectSpec` which allows for using mocks. 

BTW: Configuring the task with the extension should not be done in the task itself from my perspective. You should move this logic into the plugin.

**Comment by davidmichaelkarr** [comment]
Ok, I'll look at using ProjectSpec for some of those tests.

Concerning the task initialization code, I appreciate the suggestion.  I
did think a lot about this.  I could use a more detailed justification of
why you think this.

Balancing coupling and cohesion is always a difficult tradeoff.  In my
view, the task has the best understanding of what extension properties
should be used to initialize itself. It doesn't seem logical to me to
extract the task initialization code outside of the task and put it into
the plugin.

I can see the possibility that you're advising this because of the common
pattern of defining and configuring tasks in the build script itself.

I've designed this plugin and task so that the vast majority of use cases
will only require the developer to add the "yang" extension block to their
build script, without any additional configuration or task definition.

**Comment by bmuschko** [comment]
A task shouldn't know anything about an extension - simple reasons: better testability and decoupling.

**Comment by davidmichaelkarr** [comment]
So it's better for a plugin to know internal details of the task?  The most
important aspect of an extension is its properties. I would think an
extension with behavior would be unusual.

**Comment by bmuschko** [comment]
A plugin should usually only know the public properties and methods of a task. An extension with behavior is OK. This is more a general discussion. Would you mind taking this to the Gradle forum?
