### ISSUE TITLE
Suggestion: have "fileExists()" allow Ant-style wildcard paths

### ISSUE THREAD

**Issue by davidmichaelkarr** [nebula-plugins/nebula-test#41]
Especially when using IntegrationSpec, building a path deep into the test project directory to verify the creation of a file can be annoying, and a maintenance issue. It would be useful if the path specified with "fileExists()" could use "**" and other wildcards to verify the presence of a file deep within the project structure.

**Comment by bmuschko** [comment]
This is a just a very simple method. If you want more complex verification logic, it's very easy to write this yourself in Groovy. I don't think we want to complicate the API of this base class by additional verification methods.

**Comment by davidmichaelkarr** [comment]
I managed to find the "groovy.util.FileNameFinder" class, which provides this.
