### ISSUE TITLE
JaCoCo coverage on forked integ test

### ISSUE THREAD

**Issue by iwarapter** [nebula-plugins/nebula-test#42]
Is it possible to attach the JaCoCo agent to the forked integration tests?

**Comment by szpak** [comment]
Haven't tried with JaCoCo, but [see](https://github.com/szpak/nebula-test/commit/beaf1eaf2ce1175906d59e5cb3077fdf83dd2ea7) my PR #35 which allows to pass arguments to forked JVM to enabled remote debugging (available in 2.2.1).

**Comment by bmuschko** [comment]
@iwarapter Correct, as proposed by @szpak this should fix your issue. I am going to close this. Please reopen if you want to discuss further.

**Comment by iwarapter** [comment]
@bmuschko cheers, i'll try find which parts of the gradle jacoco plugin i'll need to add to the jvm args in the tests.

**Comment by tschulte** [comment]
I tried to generate Jacoco test reports even when using forked integration tests. For this I added the following to my test

```groovy
    def setup() {
        fork = true
        def javaagent = ManagementFactory.runtimeMXBean.inputArguments.findAll { it.startsWith('-javaagent') }.collect {
            it.replaceAll(/build.tmp.expandedArchives/, "${System.getProperty('user.dir')}/\$0")
                    .replaceAll(/build.jacoco.test.exec/, "${System.getProperty('user.dir')}/build/jacoco/$moduleName-test.exec")
        }
        jvmArguments.addAll(javaagent)
    }
```

and in build.gradle
```groovy
jacocoTestReport {
    file("$buildDir/jacoco").eachFileMatch(~/.*test\.exec/) {
        executionData(it)
    }
}
```

But this does not work. The jacoco data is only flushed to disk when the vm exits, but the forked instances do use the gradle daemon, even if the daemon is not enabled. 

Can I prevent that the forked gradle instances uses the daemon?

**Comment by bmuschko** [comment]
I haven't tried it but you might be able to avoid using the daemon by providing the command line option `--no-daemon` e.g. `runTasksSuccessfully('helloWorld', '--no-daemon')`.

**Comment by szpak** [comment]
Unfortunately when I checked it a few months ago `--no-daemon` was not supported from tooling API. It is especially painful when you run your repression tests with many different Gradle version (https://github.com/nebula-plugins/nebula-test/pull/24).

**Comment by szpak** [comment]
From the [documentation](http://gradle.org/docs/2.4/javadoc/org/gradle/tooling/BuildLauncher.html#withArguments%28java.lang.String...%29):
> Some other instructions like '--daemon' are also not supported - the tooling API always runs with the daemon.

It would be good to have at least an ability to stop daemon on demand (but `--stop` was also not possible).
