### ISSUE TITLE
Support for JDK 1.6

### ISSUE THREAD

**Issue by extr3m0** [nebula-plugins/nebula-test#50]
Hi,

thanks for the great work. This is an awesome plugin.

I was wondering whether you could enable support for JDK 1.6 as Gradle also supports JDK 1.6.

I'm a little confused because in der `bootstrap.gradle` it enables the Source/Target-Compability for JDK 1.6 but this file is never included.

I played a little with it locally but as it turns out: Just compiling it with JDK 1.6 doesn't work out of the box as the required `nebula-plugin-plugin` also relies on JDK 1.7.

Thank you very much & kind regards,
Chris

**Comment by rspieldenner** [comment]
JDK 1.6 has been end of life for a long time. JDK 1.7 was made end of life in April 2015.

The bootstrap.gradle was originially used in case the plugin-plugin was broken (and it hasn't been in a long time so we haven't used the bootstrap.gradle). Shall mark for deletion.

We have no plans of going out of our way to support JDK 1.6. We also cannot guarantee when we'll start using JDK8 features.

**Comment by extr3m0** [comment]
Thanks for the quick response. I wish we could move away from an ancient JDK! :)
