### ISSUE TITLE
Question: Gradle 2.4 support

### ISSUE THREAD

**Issue by martinda** [nebula-plugins/nebula-test#51]
When I try to run `gradle test` on the gradle-2.4 branch, the `apply plugin: 'nebula-test'` line gives:
```
A problem occurred evaluating root project 'nebula-test'.
> org/gradle/listener/BroadcastDispatch
```
Is this a problem with Nebula, with Gradle, or am I doing something wrong? Or is this branch not ready yet? Is there a workaround?

**Comment by bmuschko** [comment]
The branch is not ready yet. We are hoping to release a 2.4-compatible version soon.

**Comment by rspieldenner** [comment]
gradle-2.6 compatible released, will that work for you?

**Comment by martinda** [comment]
Yes that works for me. Thank you!
