### ISSUE TITLE
CLASSPATH_DEFAULT doesn't handle subprojects

### ISSUE THREAD

**Issue by choliver** [nebula-plugins/nebula-test#58]
`GradleRunner.CLASSPATH_DEFAULT` combines `CLASSPATH_USER_DIR` and `CLASSPATH_CACHE`.  However, that doesn't take into account Gradle subprojects (in particular, the USER_DIR filter is too restrictive when the test is in some subproject with a sibling-subproject dependency).

I'm not claiming this is a general solution, but the following currently works for me!

    public static final Predicate<URL> CLASSPATH_NO_WRAPPER = new Predicate<URL>() {
        @Override
        boolean apply(URL url) {
            !url.path.contains('/wrapper/dists')
        }
    }

    // ...

    classpathFilter = CLASSPATH_NO_WRAPPER

**Comment by jmcampanini** [comment]
ran into this as well. the fix worked for me as well. just put it in my `def setup()` in my `IntegrationSpec` tests and all good. yay!

p.s. this only failed from the command line and passed from the IDE. could it be that the `.gradle-test-kit/init.gradle` is doing things?

**Comment by DanielThomas** [comment]
Good to know - incidentally, we're considering this project deprecated, given Gradle's TestKit is now mature and most of the usability issues have been sorted out:

https://docs.gradle.org/current/userguide/test_kit.html

We might still write some helpers, in which case we'd move this project over to supporting the TestKit way of doing things.
